# Generated by Django 4.1 on 2023-05-09 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EthereumTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sender", models.CharField(max_length=42)),
                ("receiver", models.CharField(max_length=42)),
                ("value", models.FloatField()),
                ("gas_price", models.FloatField(blank=True, null=True)),
                ("gas_used", models.FloatField(blank=True, null=True)),
                ("block_number", models.IntegerField(blank=True, null=True)),
                ("transaction_fee", models.FloatField(blank=True, null=True)),
                ("is_contract_creation", models.BooleanField(default=False)),
                ("eth_timestamp", models.DateTimeField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "ethereum_transactions",
                "ordering": ["-timestamp"],
            },
        ),
    ]
