# Generated by Django 4.1 on 2023-05-09 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ethereumtransaction",
            name="eth_timestamp",
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
    ]
