# Generated by Django 4.2 on 2023-05-10 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "payments",
            "0003_suspiciousaddresses_ethereumtransaction_is_checked_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="flaggedtransaction",
            name="receiver",
            field=models.CharField(default=1, max_length=42),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="flaggedtransaction",
            name="sender",
            field=models.CharField(default=1, max_length=42),
            preserve_default=False,
        ),
    ]
